Repository svsticky/radio, pull requests merged in 2024-05, with the labels that each got.

#122 fix: remove yarn.lock and restore rc files
  .editorconfig
  .eslintrc.json
  package-lock.json
  package.json
  vite.config.js
  yarn.lock
Labels: maintainability, dependencies

#135 fix: properly bundled snow.js
  index.html
Labels: bug

#133 refactor: activity component
  src/components/Activity.jsx
  src/index.css
Labels: refactor

#134 chore: update README and adjust sample.env
  README.md
  sample.env
Labels: documentation, review
